version: "3.8"

services:
  # Router
  router:
    image: mdrahano12/calorilin-router:1.0
    container_name: calorilin-router
    restart: unless-stopped
    tty: true
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - calorilin-network

  # Backend Service
  backend-app:
    image: mdrahano12/calorilin-backend:1.4
    container_name: calorilin-backend
    restart: unless-stopped
    tty: true
    networks:
      - calorilin-network

  # Web Service
  web-app:
    image: mdrahano12/calorilin-frontend-admin:1.3
    container_name: calorilin-frontend-admin
    restart: unless-stopped
    tty: true
    networks:
      - calorilin-network

  # Web Landing Page
  web-landing-app:
    image: mdrahano12/calorilin-frontend-landingpage:1.1
    container_name: calorilin-frontend-landingpage
    restart: unless-stopped
    tty: true
    networks:
      - calorilin-network

  # Database Service
  mysql:
    image: mysql:5.7.32
    container_name: calorilin-database-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: calorilin
      MYSQL__USER: calorilin12
      MYSQL_PASSWORD: calorilin1212
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - calorilin-data:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - calorilin-network

# Docker Network
networks:
  calorilin-network:
    driver: bridge

# Volumes
volumes:
  certbot-etc:
  certbot-var:
  calorilin-data:
    driver: local
